# Generated by Django 3.2.5 on 2021-07-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('dbmanager', '0002_databaseproxyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseproxyuser',
            name='password',
            field=models.CharField(default='13kPoR03bYQVZpTj1EtL2DWQ5ro4pZ7UCudvTcPjlLnc6L603JtMGGv2aEtEvrWa', max_length=64),
        ),
        migrations.AlterField(
            model_name='databaseproxyuser',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy', to='course.student'),
        ),
    ]
