# Generated by Django 3.2.5 on 2021-07-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('dbmanager', '0003_auto_20210703_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseproxyuser',
            name='password',
            field=models.CharField(default='IHHxP8WKebPWcoCjppF5Q7Udgq1PG8hrYcDylwaZ3Kom3VIRTBZUm3IrSZqJzBRq', max_length=64),
        ),
        migrations.AlterField(
            model_name='databaseproxyuser',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.student'),
        ),
    ]
