# Generated by Django 3.2.5 on 2021-07-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('dbmanager', '0004_auto_20210703_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdatabase',
            name='course',
            field=models.ForeignKey(default='b2b02b86-dac3-11eb-93a2-0cdd241b97c0', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databasesnapshot',
            name='course',
            field=models.ForeignKey(default='b2b02b86-dac3-11eb-93a2-0cdd241b97c0', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdatabase',
            name='course',
            field=models.ForeignKey(default='b2b02b86-dac3-11eb-93a2-0cdd241b97c0', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseproxyuser',
            name='password',
            field=models.CharField(default='y2566unXQ4mCjTfrzeh0p2EmYXlIU5RUg8t6OM6ZWEPB5mWUpdqIELbIrR16jdv0', max_length=64),
        ),
    ]
