# Generated by Django 3.2.5 on 2021-07-13 20:32

import dbmanager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0006_alter_databaseproxyuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseproxyuser',
            name='password',
            field=models.CharField(default=dbmanager.models._random_password, max_length=64),
        ),
    ]
