# Generated by Django 3.2.5 on 2021-07-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0007_alter_databaseproxyuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasesnapshot',
            options={'ordering': ('request_time',)},
        ),
        migrations.RemoveField(
            model_name='databasesnapshot',
            name='course',
        ),
    ]
