# Generated by Django 3.2.5 on 2021-07-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_students'),
        ('dbmanager', '0009_databasesnapshot_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseimport',
            name='course',
            field=models.ForeignKey(default='b829204adac311eb93a20cdd241b97c0', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.course'),
            preserve_default=False,
        ),
    ]
