# Generated by Django 3.2.5 on 2021-07-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummystudent',
            options={'ordering': ('sortable_name',), 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
