# Generated by Django 3.2.5 on 2021-07-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_dummystudent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('sortable_name',), 'verbose_name': 'Student'},
        ),
    ]
