# Generated by Django 3.2.5 on 2021-07-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='_course_course_students_+', through='course.Enrollment', to='course.Student'),
        ),
    ]
