# Generated by Django 3.2.5 on 2021-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='handle',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
