# Generated by Django 3.2.5 on 2021-07-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_handle'),
        ('lab', '0002_auto_20210725_2129'),
        ('lms', '0002_auto_20210722_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvascourse',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_course', to='course.course'),
        ),
        migrations.AlterField(
            model_name='canvasstudent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_student', to='course.student'),
        ),
        migrations.CreateModel(
            name='CanvasAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_id', models.CharField(max_length=32)),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_assignment', to='lab.lab')),
            ],
        ),
    ]
