# Generated by Django 3.2.5 on 2021-07-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20210725_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasassignment',
            name='auto_update_grade',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='canvascourse',
            name='auto_update_assignment_grades',
            field=models.BooleanField(default=False),
        ),
    ]
