# Generated by Django 3.2 on 2021-04-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='lab.course'),
        ),
        migrations.AddConstraint(
            model_name='problemonlab',
            constraint=models.UniqueConstraint(fields=('problem',), name='problem_unique'),
        ),
    ]
