# Generated by Django 3.2.5 on 2021-07-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptresults',
            name='data_file',
            field=models.FileField(upload_to='lab/upload/attempt/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='problemschema',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='lab/upload/schema/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='problemtabledata',
            name='data_file',
            field=models.FileField(upload_to='lab/upload/table_data/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='result_data_file',
            field=models.FileField(default=None, null=True, upload_to='lab/upload/correct/%Y/%m/%d/'),
        ),
    ]
