# Generated by Django 3.2 on 2021-04-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20210413_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='lab.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lab.student')),
            ],
            options={
                'ordering': ('when',),
            },
        ),
    ]
