# Generated by Django 3.2 on 2021-04-13 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_problemattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemattempt',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
    ]
