# Generated by Django 3.2 on 2021-04-13 21:55

from django.db import migrations, models
import django.db.models.deletion
import pathlib
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_problemattempt_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('number', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='schema_file',
            field=models.FileField(default=None, null=True, upload_to=pathlib.PurePosixPath('/home/kathy/PycharmProjects/sql_lab/upload')),
        ),
        migrations.AddField(
            model_name='problem',
            name='schema_filename',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestCaseData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('data_file', models.FileField(upload_to=pathlib.PurePosixPath('/home/kathy/PycharmProjects/sql_lab/upload'))),
                ('data_filename', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=30)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.problemtestcase')),
            ],
            options={
                'ordering': ('table_name',),
            },
        ),
        migrations.AddField(
            model_name='problemtestcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='lab.problem'),
        ),
    ]
