# Generated by Django 3.2 on 2021-04-14 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20210413_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='lab.instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students', through='lab.Enrollment', to='lab.Student'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
