# Generated by Django 3.2 on 2021-04-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20210414_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='after_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
