# Generated by Django 3.2 on 2021-04-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20210415_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='validation_token',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
