# Generated by Django 3.2 on 2021-04-16 01:10

from django.db import migrations, models
import django.db.models.deletion
import pathlib
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_alter_problem_validation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('file', models.FileField(default=None, null=True, upload_to=pathlib.PurePosixPath('/home/kathy/PycharmProjects/sql_lab/upload'))),
                ('filename', models.CharField(default=None, max_length=100, null=True)),
                ('status', models.CharField(choices=[('M', 'Missing'), ('P', 'Processing'), ('V', 'Valid'), ('I', 'Invalid')], default='M', max_length=1)),
                ('table_names', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='schema_file',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='schema_filename',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='schema_status',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='table_names',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='validation_token',
        ),
        migrations.AddField(
            model_name='problem',
            name='schema',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='referenced_problems', to='lab.problemschema'),
        ),
    ]
