# Generated by Django 3.2 on 2021-04-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_auto_20210416_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtestcasetabledata',
            name='table_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.problemtabledata'),
        ),
    ]
