# Generated by Django 3.2 on 2021-04-18 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_alter_problemtestcasetabledata_table_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtestcasetabledata',
            name='table_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='lab.problemtabledata'),
        ),
        migrations.AlterField(
            model_name='problemtestcasetabledata',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_data_set', to='lab.problemtestcase'),
        ),
        migrations.AddConstraint(
            model_name='problemtestcasetabledata',
            constraint=models.UniqueConstraint(fields=('test_case', 'table_name'), name='unique_mapping_for_table'),
        ),
    ]
