# Generated by Django 3.2 on 2021-04-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_auto_20210419_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptresults',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemattempt',
            name='score',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
