# Generated by Django 3.2 on 2021-04-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_auto_20210420_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='starter_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
