# Generated by Django 3.2 on 2021-05-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_problemtestcase_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_course_title'),
        ),
    ]
