# Generated by Django 3.2 on 2021-05-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_course_unique_course_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_title',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('instructor', 'title'), name='unique_course_title'),
        ),
    ]
