# Generated by Django 3.2 on 2021-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0020_auto_20210511_1844'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lab',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='lab_title_unique'),
        ),
    ]
