# Generated by Django 3.2 on 2021-05-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_lab_lab_title_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
