# Generated by Django 3.2 on 2021-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_problem_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProblemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'custom_student_problem_scores',
                'managed': False,
            },
        ),
    ]
