# Generated by Django 3.2 on 2021-05-15 00:34

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0023_studentproblemscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyStudent',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lab.student')),
                ('alter_ego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lab.instructor')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'abstract': False,
            },
            bases=('lab.student',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
