# Generated by Django 3.2 on 2021-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0024_dummystudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
