# Generated by Django 3.2 on 2021-05-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0025_student_is_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='lab.Enrollment', to='lab.Student'),
        ),
    ]
