# Generated by Django 3.2 on 2021-06-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0026_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attemptresults',
            name='data_file',
            field=models.FileField(upload_to='attempt/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='problemschema',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='schema/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='problemtabledata',
            name='data_file',
            field=models.FileField(upload_to='table_data/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='result_data_file',
            field=models.FileField(default=None, null=True, upload_to='correct/%Y/%m/%d/'),
        ),
    ]
