# Generated by Django 3.2 on 2021-06-30 19:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0027_auto_20210628_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSetupLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.student')),
            ],
        ),
    ]
