# Generated by Django 3.2 on 2021-06-30 19:53

from django.db import migrations, models
import lab.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0028_accountsetuplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsetuplink',
            name='id',
            field=models.CharField(default=lab.models._random_link_id, max_length=32, primary_key=True, serialize=False),
        ),
    ]
